DIR_SCRAPING_JOBS = 'scraping_jobs'
DIR_DATABASE = 'database'
NAME_DATABASE_ON_MARKET = 'db_on_market.pkl'
NAME_DATABASE_OFF_MARKET = 'db_off_market.pkl'
NAME_DATABASE_NEW_ON_MARKET = 'db_new_on_market.pkl'

PATH_SCRAPING_JOBS = f'./data/{DIR_SCRAPING_JOBS}'
PATH_DATABASE = f'./data/{DIR_DATABASE}'
PATH_DATABASE_ON_MARKET = PATH_DATABASE + '/' + NAME_DATABASE_ON_MARKET
PATH_DATABASE_OFF_MARKET = PATH_DATABASE + '/' + NAME_DATABASE_OFF_MARKET
PATH_DATABASE_NEW_ON_MARKET = PATH_DATABASE + '/' + NAME_DATABASE_NEW_ON_MARKET

